
spring:
  cloud:
    gateway:
      routes:
        - id: gateway-client1 #id是唯一的
          #uri: lb://gateway-client #被代理的服务的uri
          uri: http://localhost:9090
          predicates:
            - Path=/test/**
            #- Cookie=test,123456
            #- Method=POST
            #- Header=test,(.*?)
            #- Host=**.testhost.org
            #- Query=ljs,xs
            #- Weight=service,4
          filters:
            - StripPrefix=1